baseURL: "/"
title: Moolrin
theme: somrat
paginate: '6'
summaryLength: '10'
disableLanguages: []
googleAnalytics: ''
disqusShortname: ''
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  author: MOOLRIN
  description: sajinman
  favicon: images/favicon_mooool.png
  logo_dark: images/logo_blank.png
  logo_light: images/logo_blank.png
  logo_width: 0px
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap
      - link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css
      - link: plugins/hover/hover.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/owl-carousel/owl.carousel.min.css
      - link: plugins/owl-carousel/owl.theme.default.min.css
      - link: plugins/text-animation/text-animation.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/wow.min.js
      - link: plugins/text-animation/text-animation.js
      - link: plugins/jquery.waypoints.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/owl-carousel/owl.carousel.min.js
  social:
    - icon: fab fa-tree
      link: https://www.linktr.ee/moolrin
    - icon: fab fa-twitter
      link: https://twitter.com/MOOLRIN
    - icon: fab fa-instagram
      link: https://www.instagram.com/MOOLRIN

Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: About me
          pre: '#'
          url: about
          weight: 2
        - name: Portfolio
          pre: '#'
          url: portfolio
          weight: 3
    weight: 1s